apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
  labels:
    app: secure-app
spec:
  securityContext:
    runAsUser: 1000       # Ensures the pod runs as a non-root user
    runAsNonRoot: true    # Prevents the pod from running as root
  containers:
  - name: secure-container
    image: nginx          # Using an Nginx container
    securityContext:
      readOnlyRootFilesystem: true  # Makes root filesystem read-only
      allowPrivilegeEscalation: false  # Prevents privilege escalation
      capabilities:
        drop:
          - ALL  # Drops all unnecessary Linux capabilities
    ports:
    - containerPort: 80
